package at.zuhauseambach.mobile.neu;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
  static final int BLUE=Color.rgb(18,76,125), GREEN=Color.rgb(73,143,35), BG=Color.rgb(244,248,251), RED=Color.rgb(190,35,35);
  LinearLayout root,content; TextView status; JSONObject data=new JSONObject();
  String base="http://10.0.0.24:8765"; final ExecutorService io=Executors.newSingleThreadExecutor();
  final SimpleDateFormat ymd=new SimpleDateFormat("yyyy-MM-dd",Locale.GERMANY);

  @Override public void onCreate(Bundle b){super.onCreate(b);base=getPreferences(MODE_PRIVATE).getString("base",base);build();refresh();}
  @Override protected void onDestroy(){io.shutdownNow();super.onDestroy();}
  int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
  TextView t(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.rgb(22,49,73));v.setPadding(dp(5),dp(6),dp(5),dp(6));if(bold)v.setTypeface(null,1);return v;}
  Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setTextSize(15);return x;}
  EditText f(String h){EditText e=new EditText(this);e.setHint(h);e.setSingleLine(true);e.setTextSize(16);return e;}
  LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(14),dp(12),dp(14),dp(12));GradientDrawable g=new GradientDrawable();g.setColor(Color.WHITE);g.setCornerRadius(dp(14));g.setStroke(dp(1),Color.rgb(210,220,230));l.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(10),dp(8),dp(10),dp(8));l.setLayoutParams(p);return l;}

  void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
    LinearLayout h=new LinearLayout(this);h.setOrientation(LinearLayout.VERTICAL);h.setPadding(dp(20),dp(18),dp(20),dp(14));h.setBackgroundColor(BLUE);TextView a=t("Zuhause am Bach",17,true);a.setTextColor(Color.WHITE);h.addView(a);TextView q=t("Mobil NEU V100",34,true);q.setTextColor(Color.WHITE);h.addView(q);root.addView(h);
    LinearLayout s=card();status=t("Verbinde mit Hotel-PC …",17,true);s.addView(status);LinearLayout r=new LinearLayout(this);Button up=b("Aktualisieren");up.setOnClickListener(v->refresh());Button cfg=b("Verbindung");cfg.setOnClickListener(v->config());r.addView(up,new LinearLayout.LayoutParams(0,-2,1));r.addView(cfg,new LinearLayout.LayoutParams(0,-2,1));s.addView(r);root.addView(s);
    HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout nav=new LinearLayout(this);String[] nn={"Heute","Zimmer","Gäste","Check-in","Artikel","Aufgaben"};for(String n:nn){Button x=b(n);x.setOnClickListener(v->show(((Button)v).getText().toString()));nav.addView(x);}hs.addView(nav);root.addView(hs);
    ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(4),dp(4),dp(4),dp(40));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}

  void config(){EditText e=f("http://10.0.0.24:8765");e.setText(base);new AlertDialog.Builder(this).setTitle("Hotel-PC Verbindung").setView(e).setNegativeButton("Abbrechen",null).setPositiveButton("Speichern",(d,w)->{base=e.getText().toString().trim().replaceAll("/+$","");getPreferences(MODE_PRIVATE).edit().putString("base",base).apply();refresh();}).show();}
  void refresh(){status.setText("Verbinde mit "+base+" …");io.execute(()->{try{JSONObject o=new JSONObject(http("GET",base+"/data/mobile_data.json",null));runOnUiThread(()->{data=o;status.setText("✓ Verbunden · Daten geladen");status.setTextColor(GREEN);show("Heute");});}catch(Exception e){runOnUiThread(()->{status.setText("✕ Keine Verbindung: "+e.getMessage());status.setTextColor(RED);content.removeAllViews();LinearLayout c=card();c.addView(t("Verbindungstest",23,true));c.addView(t("Server: "+base,16,false));c.addView(t("Im Handy-Browser muss funktionieren:\n"+base+"/api/status",16,false));content.addView(c);});}});}
  JSONArray ar(String k){JSONArray a=data.optJSONArray(k);return a==null?new JSONArray():a;}
  String v(JSONObject o,String...k){for(String x:k){String s=o.optString(x,"").trim();if(!s.isEmpty())return s;}return "";}
  String guest(JSONObject o){return v(o,"guestName","guest","name");}
  boolean cancel(JSONObject o){String s=o.optString("status","").toLowerCase();return s.contains("storn")||s.contains("cancel")||s.contains("abgesagt");}
  String today(){return ymd.format(new Date());} boolean isToday(String s){return s!=null&&s.startsWith(today());}
  Date d(String s){try{return ymd.parse(s.substring(0,10));}catch(Exception e){return null;}}
  void show(String n){content.removeAllViews();if(n.equals("Zimmer"))rooms();else if(n.equals("Gäste"))guests();else if(n.equals("Check-in"))checkin();else if(n.equals("Artikel"))articles();else if(n.equals("Aufgaben"))tasks();else home();}
  void bookingLine(LinearLayout c,JSONObject x,String badge){c.addView(t(badge+"  "+guest(x),18,true));c.addView(t(v(x,"room")+" · "+v(x,"arrival")+" → "+v(x,"departure")+" · "+x.optInt("persons",1)+" Pers.",14,false));String p=v(x,"phone");if(!p.isEmpty()){Button z=b("Anrufen "+p);z.setOnClickListener(w->{try{startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+p.replace(" ",""))));}catch(Exception ignored){}});c.addView(z);}}

  void home(){LinearLayout c=card();c.addView(t("Heute",24,true));int an=0,ab=0,haus=0;JSONArray bs=ar("bookings");Date T=d(today());for(int i=0;i<bs.length();i++){JSONObject x=bs.optJSONObject(i);if(x==null||cancel(x))continue;if(isToday(v(x,"arrival"))){bookingLine(c,x,"ANREISE");an++;}if(isToday(v(x,"departure"))){bookingLine(c,x,"ABREISE");ab++;}Date A=d(v(x,"arrival")),D=d(v(x,"departure"));if(A!=null&&D!=null&&T!=null&&A.before(T)&&D.after(T)){bookingLine(c,x,"IM HAUS");haus++;}}if(an+ab+haus==0)c.addView(t("Heute keine An- oder Abreise eingetragen.",16,false));content.addView(c);LinearLayout k=card();k.addView(t("Anreisen: "+an+"   ·   Abreisen: "+ab+"   ·   Im Haus: "+haus,17,true));content.addView(k);}
  void rooms(){LinearLayout c=card();c.addView(t("Zimmer",24,true));JSONArray rs=ar("rooms");if(rs.length()==0)c.addView(t("Keine Zimmerdaten vorhanden.",16,false));for(int i=0;i<rs.length();i++){JSONObject r=rs.optJSONObject(i);if(r!=null){c.addView(t(v(r,"name","room"),19,true));c.addView(t("Status: "+v(r,"status","state"),15,false));}}content.addView(c);}
  void guests(){LinearLayout c=card();c.addView(t("Nächste Gäste",24,true));JSONArray bs=ar("bookings");List<JSONObject> l=new ArrayList<>();Date T=d(today());for(int i=0;i<bs.length();i++){JSONObject x=bs.optJSONObject(i);Date A=x==null?null:d(v(x,"arrival"));if(x!=null&&!cancel(x)&&A!=null&&T!=null&&!A.before(T))l.add(x);}Collections.sort(l,(x,y)->v(x,"arrival").compareTo(v(y,"arrival")));for(JSONObject x:l)bookingLine(c,x,v(x,"arrival"));if(l.isEmpty())c.addView(t("Keine kommenden Gäste.",16,false));content.addView(c);}

  void checkin(){JSONArray bs=ar("bookings");List<JSONObject> l=new ArrayList<>();Date T=d(today()),L=new Date(System.currentTimeMillis()+14L*86400000L);for(int i=0;i<bs.length();i++){JSONObject x=bs.optJSONObject(i);Date A=x==null?null:d(v(x,"arrival"));if(x!=null&&!cancel(x)&&A!=null&&T!=null&&!A.before(T)&&!A.after(L))l.add(x);}LinearLayout c=card();c.addView(t("Gäste-Check-in",24,true));if(l.isEmpty()){c.addView(t("Keine Anreise in den nächsten 14 Tagen.",16,false));content.addView(c);return;}List<String> lab=new ArrayList<>();for(JSONObject x:l)lab.add(v(x,"arrival")+" · "+guest(x)+" · "+v(x,"room"));Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,lab));c.addView(sp);
    EditText name=f("Vor- und Familienname *"),birth=f("Geburtsdatum YYYY-MM-DD *"),gender=f("Geschlecht *"),nat=f("Staatsangehörigkeit *"),street=f("Straße / Hausnummer *"),plz=f("PLZ *"),city=f("Ort *"),country=f("Wohnsitzland *"),phone=f("Telefon"),email=f("E-Mail");for(EditText e:new EditText[]{name,birth,gender,nat,street,plz,city,country,phone,email})c.addView(e);
    Runnable fill=()->{JSONObject x=l.get(sp.getSelectedItemPosition());name.setText(guest(x));phone.setText(v(x,"phone"));email.setText(v(x,"email"));plz.setText(v(x,"plz"));city.setText(v(x,"city"));country.setText(v(x,"country"));};fill.run();sp.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?>p,View w,int pos,long id){fill.run();}public void onNothingSelected(android.widget.AdapterView<?>p){}});
    c.addView(t("Unterschrift *",16,true));SignatureView sig=new SignatureView(this);c.addView(sig,new LinearLayout.LayoutParams(-1,dp(160)));Button clear=b("Unterschrift löschen");clear.setOnClickListener(w->sig.clear());c.addView(clear);CheckBox ok=new CheckBox(this);ok.setText("Angaben sind richtig und dürfen für Melde- und Beherbergungszwecke verarbeitet werden.");c.addView(ok);
    Button save=b("Check-in am PC speichern");save.setOnClickListener(w->{JSONObject x=l.get(sp.getSelectedItemPosition());if(name.getText().toString().trim().isEmpty()||birth.getText().toString().trim().isEmpty()||gender.getText().toString().trim().isEmpty()||nat.getText().toString().trim().isEmpty()||street.getText().toString().trim().isEmpty()||plz.getText().toString().trim().isEmpty()||city.getText().toString().trim().isEmpty()||country.getText().toString().trim().isEmpty()||!ok.isChecked()||sig.empty){Toast.makeText(this,"Pflichtfelder, Zustimmung und Unterschrift fehlen.",Toast.LENGTH_LONG).show();return;}try{JSONObject p=new JSONObject();p.put("guest",name.getText().toString().trim());p.put("birth",birth.getText().toString().trim());p.put("gender",gender.getText().toString().trim());p.put("nationality",nat.getText().toString().trim());p.put("street",street.getText().toString().trim());p.put("plz",plz.getText().toString().trim());p.put("city",city.getText().toString().trim());p.put("country",country.getText().toString().trim());p.put("phone",phone.getText().toString().trim());p.put("email",email.getText().toString().trim());p.put("privacy_accepted",true);p.put("companions",new JSONArray());p.put("signature",sig.dataUrl());JSONObject pack=new JSONObject();pack.put("format","zab-guest-checkin-v1");pack.put("created_at",new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.GERMANY).format(new Date()));pack.put("booking_id",v(x,"id"));pack.put("arrival",v(x,"arrival"));pack.put("payload",p);String fn="ZAB_CHECKIN_"+name.getText().toString().trim().replaceAll("[^A-Za-z0-9_-]+","_")+"_"+v(x,"arrival")+".json";JSONObject body=new JSONObject();body.put("file_name",fn);body.put("package",pack);post("/api/checkin-file",body,"Check-in gespeichert");}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}});c.addView(save);content.addView(c);}

  void articles(){LinearLayout c=card();c.addView(t("Artikel auf Gast buchen",24,true));JSONArray bs=ar("bookings");List<JSONObject> l=new ArrayList<>();List<String> lab=new ArrayList<>();for(int i=0;i<bs.length();i++){JSONObject x=bs.optJSONObject(i);if(x!=null&&!cancel(x)){l.add(x);lab.add(guest(x)+" · "+v(x,"room"));}}if(l.isEmpty()){c.addView(t("Keine Buchung vorhanden.",16,false));content.addView(c);return;}Spinner sp=new Spinner(this);sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,lab));c.addView(sp);EditText item=f("Artikel, z.B. Kaffee"),qty=f("Menge"),price=f("Preis in €");qty.setText("1");price.setText("0");c.addView(item);c.addView(qty);c.addView(price);Button save=b("Artikel speichern");save.setOnClickListener(w->{try{JSONObject o=new JSONObject();o.put("bookingId",v(l.get(sp.getSelectedItemPosition()),"id"));o.put("item",item.getText().toString().trim());o.put("qty",Double.parseDouble(qty.getText().toString().replace(',','.')));o.put("price",Double.parseDouble(price.getText().toString().replace(',','.')));post("/api/extras",o,"Artikel gespeichert");}catch(Exception e){Toast.makeText(this,"Eingaben prüfen: "+e.getMessage(),Toast.LENGTH_LONG).show();}});c.addView(save);content.addView(c);}
  void tasks(){LinearLayout c=card();c.addView(t("Aufgaben",24,true));JSONArray bs=ar("bookings");int n=0;for(int i=0;i<bs.length();i++){JSONObject x=bs.optJSONObject(i);if(x==null||cancel(x))continue;if(isToday(v(x,"arrival"))){c.addView(t("14:00 · "+guest(x)+": Zimmer und Check-in vorbereiten.",16,true));n++;}if(isToday(v(x,"departure"))){c.addView(t("10:00 · "+guest(x)+": Checkout, Rechnung und Ortstaxe prüfen.",16,true));n++;}if(v(x,"phone").isEmpty()){Date A=d(v(x,"arrival"));if(A!=null&&A.after(new Date())){c.addView(t("Prüfen · "+guest(x)+": Telefonnummer fehlt.",16,false));n++;}}}if(n==0)c.addView(t("Keine dringenden Aufgaben erkannt.",16,false));content.addView(c);}

  void post(String path,JSONObject body,String ok){status.setText("Speichere am PC …");io.execute(()->{try{JSONObject o=new JSONObject(http("POST",base+path,body.toString()));if(!o.optBoolean("ok",true))throw new IOException(o.optString("error","Serverfehler"));runOnUiThread(()->{status.setText("✓ "+ok);status.setTextColor(GREEN);Toast.makeText(this,ok,Toast.LENGTH_LONG).show();refresh();});}catch(Exception e){runOnUiThread(()->{status.setText("✕ Speichern fehlgeschlagen: "+e.getMessage());status.setTextColor(RED);Toast.makeText(this,"Nicht gespeichert: "+e.getMessage(),Toast.LENGTH_LONG).show();});}});}
  String http(String method,String url,String body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod(method);c.setConnectTimeout(5000);c.setReadTimeout(8000);c.setRequestProperty("Accept","application/json");c.setRequestProperty("Cache-Control","no-cache");if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");try(OutputStream os=c.getOutputStream()){os.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();StringBuilder sb=new StringBuilder();if(in!=null)try(BufferedReader br=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line;while((line=br.readLine())!=null)sb.append(line);}if(code<200||code>=300)throw new IOException("HTTP "+code+" "+sb);return sb.toString();}

  public static class SignatureView extends View {Paint p=new Paint(1);Path path=new Path();Bitmap bmp;Canvas cv;boolean empty=true;public SignatureView(Context c){super(c);p.setColor(Color.rgb(20,50,75));p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setStrokeCap(Paint.Cap.ROUND);setBackgroundColor(Color.WHITE);}protected void onSizeChanged(int w,int h,int ow,int oh){if(w>0&&h>0){bmp=Bitmap.createBitmap(w,h,Bitmap.Config.ARGB_8888);cv=new Canvas(bmp);cv.drawColor(Color.WHITE);}}protected void onDraw(Canvas c){super.onDraw(c);if(bmp!=null)c.drawBitmap(bmp,0,0,null);c.drawPath(path,p);}public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(e.getAction()==MotionEvent.ACTION_DOWN){path.moveTo(x,y);return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){path.lineTo(x,y);empty=false;invalidate();return true;}if(e.getAction()==MotionEvent.ACTION_UP){if(cv!=null)cv.drawPath(path,p);path.reset();invalidate();return true;}return true;}void clear(){if(cv!=null){cv.drawColor(Color.WHITE);path.reset();empty=true;invalidate();}}String dataUrl(){if(bmp==null)return "";ByteArrayOutputStream out=new ByteArrayOutputStream();bmp.compress(Bitmap.CompressFormat.PNG,80,out);return "data:image/png;base64,"+android.util.Base64.encodeToString(out.toByteArray(),android.util.Base64.NO_WRAP);}}
}
